const docsCreated = {
    sandbox: false,
    external_id: "1090",
    open_id: 374,
    token: "dd698305-d87a-48bc-9692-41467864257b",
    name: "Contrato de presta\\u00e7\\u00e3o de servi\\u00e7os faturado",
    folder_path: "/",
    status: "pending",
    lang: "pt-br",
    original_file:
        "https://zapsign.s3.amazonaws.com/2022/12/pdf/b0cc04d1-5c37-4546-a25a-dfe5eb267fda/f7aa7930-8ebe-4502-a5d5-a8f11abaf907.pdf",
    signed_file: null,
    extra_docs: [],
    created_through: "api-template",
    deleted: false,
    deleted_at: null,
    signed_file_only_finished: false,
    disable_signer_emails: false,
    brand_logo: "https://russelservicos.com.br/wp-content/themes/ferado/images/logo-branca.png",
    brand_primary_color: "#E1383E",
    created_at: "2022-12-19T14:06:23.915294Z",
    last_update_at: "2022-12-19T14:06:23.915314Z",
    created_by: { email: "admin@russelservicos.com.br" },
    template: { token: "ced37429-5a85-4c7c-8961-0cf7b6899243" },
    signers: [
        {
            external_id: "",
            sign_url: "https://app.zapsign.com.br/verificar/4ebb0366-f558-4962-a130-9b11bfe2c068",
            token: "4ebb0366-f558-4962-a130-9b11bfe2c068",
            status: "new",
            name: "joao victor",
            lock_name: true,
            email: "jvictor.braga@yahoo.com",
            lock_email: true,
            hide_email: false,
            blank_email: false,
            phone_country: "55",
            phone_number: "",
            lock_phone: false,
            hide_phone: false,
            blank_phone: false,
            times_viewed: 0,
            last_view_at: null,
            signed_at: null,
            auth_mode: "assinaturaTela",
            qualification: "",
            require_selfie_photo: false,
            require_document_photo: false,
            geo_latitude: null,
            geo_longitude: null,
            redirect_link: "",
            signature_image: null,
            visto_image: null,
            document_photo_url: "",
            document_verse_photo_url: "",
            selfie_photo_url: "",
            selfie_photo_url2: "",
            send_via: "email",
        },
        {
            external_id: "",
            sign_url: "https://app.zapsign.com.br/verificar/92168dcb-b15c-4e8e-899d-e30e118a6771",
            token: "92168dcb-b15c-4e8e-899d-e30e118a6771",
            status: "new",
            name: "Hugo Leonardo da Silva Russel",
            lock_name: true,
            email: "admin@russelservicos.com.br",
            lock_email: true,
            hide_email: false,
            blank_email: false,
            phone_country: "55",
            phone_number: "21998658883",
            lock_phone: true,
            hide_phone: false,
            blank_phone: false,
            times_viewed: 0,
            last_view_at: null,
            signed_at: null,
            auth_mode: "assinaturaTela",
            qualification: "",
            require_selfie_photo: false,
            require_document_photo: false,
            geo_latitude: null,
            geo_longitude: null,
            redirect_link: "",
            signature_image: null,
            visto_image: null,
            document_photo_url: "",
            document_verse_photo_url: "",
            selfie_photo_url: "",
            selfie_photo_url2: "",
            send_via: "email",
        },
    ],
    answers: [],
    auto_reminder: 0,
    event_type: "doc_created",
};

const docsSigned = {
    sandbox: false,
    external_id: "1095",
    open_id: 373,
    token: "6922035b-1ea8-4f85-91b2-434a2ec7577a",
    name: "Contrato de presta\\u00e7\\u00e3o de servi\\u00e7os faturado",
    folder_path: "/",
    status: "pending",
    lang: "pt-br",
    original_file:
        "https://zapsign.s3.amazonaws.com/2022/12/pdf/3f057d7e-ddc4-4afb-a684-3995df89464b/95db058e-e3b2-4a7e-bd5c-3f086b84897f.pdf",
    signed_file:
        "https://zapsign.s3.amazonaws.com/2022/12/pdf/318123c3-5cc8-4080-8990-66f26c954a33/ea755047-e03f-4fac-91b1-79abbcf9b056.pdf",
    extra_docs: [],
    created_through: "api-template",
    deleted: false,
    deleted_at: null,
    signed_file_only_finished: false,
    disable_signer_emails: false,
    brand_logo: "https://russelservicos.com.br/wp-content/themes/ferado/images/logo-branca.png",
    brand_primary_color: "#E1383E",
    created_at: "2022-12-15T12:15:10.000339Z",
    last_update_at: "2022-12-15T12:17:38.400211Z",
    created_by: { email: "admin@russelservicos.com.br" },
    template: { token: "ced37429-5a85-4c7c-8961-0cf7b6899243" },
    signers: [
        {
            external_id: "",
            sign_url: "https://app.zapsign.com.br/verificar/b48f04e2-51eb-4a19-89e0-8a94107da8d2",
            token: "b48f04e2-51eb-4a19-89e0-8a94107da8d2",
            status: "signed",
            name: "Designer Russel",
            lock_name: true,
            email: "designer@empresa.russelservicos.com.br",
            lock_email: true,
            hide_email: false,
            blank_email: false,
            phone_country: "55",
            phone_number: "21222303979",
            lock_phone: false,
            hide_phone: false,
            blank_phone: false,
            times_viewed: 1,
            last_view_at: "2022-12-15T12:16:26.614324Z",
            signed_at: "2022-12-15T12:17:35.986063Z",
            auth_mode: "assinaturaTela",
            qualification: "",
            require_selfie_photo: false,
            require_document_photo: false,
            geo_latitude: "-22.894526",
            geo_longitude: "-43.184393",
            redirect_link: "",
            signature_image:
                "https://zapsign.s3.amazonaws.com/2022/12/files/dee1b086-f262-41ad-96e1-812d067a00bc/03a59717-3b26-42d7-9152-c4ad8dea5dbd.png",
            visto_image: "",
            document_photo_url: "",
            document_verse_photo_url: "",
            selfie_photo_url: "",
            selfie_photo_url2: "",
            send_via: "email",
        },
        {
            external_id: "",
            sign_url: "https://app.zapsign.com.br/verificar/91d232d5-7567-41b4-ba1b-2989c7962927",
            token: "91d232d5-7567-41b4-ba1b-2989c7962927",
            status: "new",
            name: "Hugo Leonardo da Silva Russel",
            lock_name: true,
            email: "admin@russelservicos.com.br",
            lock_email: true,
            hide_email: false,
            blank_email: false,
            phone_country: "55",
            phone_number: "21998658883",
            lock_phone: true,
            hide_phone: false,
            blank_phone: false,
            times_viewed: 0,
            last_view_at: null,
            signed_at: null,
            auth_mode: "assinaturaTela",
            qualification: "",
            require_selfie_photo: false,
            require_document_photo: false,
            geo_latitude: null,
            geo_longitude: null,
            redirect_link: "",
            signature_image: null,
            visto_image: null,
            document_photo_url: "",
            document_verse_photo_url: "",
            selfie_photo_url: "",
            selfie_photo_url2: "",
            send_via: "email",
        },
    ],
    answers: [
        { variable: "TIPO CONTRATO", value: "Di\\u00e1ria" },
        {
            variable: "DESCRI\\u00c7\\u00c3O ITENS",
            value: "Auxiliar de Servi\\u00e7os Gerais (ASG) - Meia Di\\u00e1ria | 1 | 5 dias \\u00fateis;07h \\u00e0s 17h.\\n",
        },
        { variable: "valor do contrato", value: "R$ 900,00" },
        { variable: "ID", value: "1095" },
        { variable: "NOME EMPRESA", value: "DESIGNER RUSSEL LTDA INC CO" },
        { variable: "CNPJ EMPRESA", value: "89912645000104" },
        { variable: "NOME CLIENTE", value: "Designer Russel" },
        { variable: "EMAIL CLIENTE", value: "designer@empresa.russelservicos.com.br" },
    ],
    auto_reminder: 0,
    event_type: "doc_signed",
    signer_who_signed: {
        external_id: "",
        sign_url: "https://app.zapsign.com.br/verificar/b48f04e2-51eb-4a19-89e0-8a94107da8d2",
        token: "b48f04e2-51eb-4a19-89e0-8a94107da8d2",
        status: "signed",
        name: "Designer Russel",
        lock_name: true,
        email: "designer@empresa.russelservicos.com.br",
        lock_email: true,
        hide_email: false,
        blank_email: false,
        phone_country: "55",
        phone_number: "21222303979",
        lock_phone: false,
        hide_phone: false,
        blank_phone: false,
        times_viewed: 1,
        last_view_at: "2022-12-15T12:16:26.614324Z",
        signed_at: "2022-12-15T12:17:35.986063Z",
        auth_mode: "assinaturaTela",
        qualification: "",
        require_selfie_photo: false,
        require_document_photo: false,
        geo_latitude: "-22.894526",
        geo_longitude: "-43.184393",
        redirect_link: "",
        signature_image:
            "https://zapsign.s3.amazonaws.com/2022/12/files/dee1b086-f262-41ad-96e1-812d067a00bc/03a59717-3b26-42d7-9152-c4ad8dea5dbd.png",
        visto_image: "",
        document_photo_url: "",
        document_verse_photo_url: "",
        selfie_photo_url: "",
        selfie_photo_url2: "",
        send_via: "email",
    },
};

export { docsCreated, docsSigned };
